services:
  database:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my-blog-db
      TZ: Asia/Tokyo
    restart: always
    ports:
      - 5432:5432
    networks:
      - my-blog-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
networks:
  my-blog-network:
    external: true
